/*You are given two strings s and t.
String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.*/

/*Example 1:
Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.*/

class Solution {
    public char findTheDifference(String s, String t) {
        int total=0;
        for (int i=0;i<t.length();i++){
            total = total + t.charAt(i);
        }

        for(int i=0;i<s.length();i++){
            total=total-s.charAt(i);
        }
        return (char)total;
    }
}

/*we sum up ASCII value of characters of first string and subtract it with ASCII value of all char for second string. 
  Then we remain with the difference, that is ASCII value of added char*/
